version: '3'

tasks:
  clean-docker:
    desc: Clean up docker images and volumes
    cmds:
      - docker system prune -fa --volumes

  sync:
    desc: Sync the Taskfile.yaml to ~
    cmds:
      - gh repo clone dodizzle/taskfile /tmp/taskfile
      - cp /tmp/taskfile/Taskfile.yaml ~/
      - rm -rf /tmp/taskfile

  edit-task-file:
    desc: Open Taskfile.yaml in vs code editor
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - gh repo clone dodizzle/taskfile /tmp/taskfile
      - code /tmp/taskfile/Taskfile.yaml