version: '3'

tasks:
  docker build:
    desc: docker build
    cmds:
    - docker build -t webservice:latest .

  docker up:
    desc: docker compose up
    cmds:
    - docker-compose up -d
    - docker container logs -f webservice

  docker down: 
    desc: docker compose down
    cmds:
    - docker-compose down --remove-orphans
    - rm -rf pgdata
    - docker system prune -f

  sync:
    desc: Sync the Taskfile.yaml to ~
    cmds:
      - gh repo clone dodizzle/goUtilities /tmp/dodizzle/taskfile
      - cp /tmp/dodizzle/taskfile/Taskfile.yaml ~/
      - rm -rf /tmp/dodizzle/goUtilities

  taskfile:
    desc: Open Taskfile.yaml in vs code editor
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - code ~/GO/src/github.com/dodizzle/taskfile/Taskfile.yaml