version: '3'

tasks:
  sync:
    desc: Sync the Taskfile.yaml to ~
    cmds:
      - gh repo clone dodizzle/goUtilities /tmp/dodizzle/taskfile
      - cp /tmp/dodizzle/taskfile/Taskfile.yaml ~/
      - rm -rf /tmp/dodizzle/goUtilities


  taskfile:
    desc: Open Taskfile.yaml in vs code editor
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - code ~/GO/src/github.com/dodizzle/taskfile/Taskfile.yaml