version: '3'

tasks:
  edit-bash-profile:
    desc: Edit bash profile
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - code ~/.bash_profile
  source-bash-profile:
    desc: Source bash profile
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - . ~/.bash_profile
  clean-docker:
    desc: Clean up docker images and volumes
    cmds:
      - docker system prune -fa --volumes

  sync:
    desc: Sync the Taskfile.yaml to ~
    cmds:
      - |
        if [ $(task check-dir DIR_PATH=/tmp/taskfile) = "false" ]; then
          gh repo clone dodizzle/taskfile /tmp/taskfile
        else
          cd /tmp/taskfile && git pull
        fi
      - cp /tmp/taskfile/Taskfile.yaml ~/

  edit-task-file:
    desc: Open Taskfile.yaml in vs code editor
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - |
        if [ $(task check-dir DIR_PATH=/tmp/taskfile) = "false" ]; then
          gh repo clone dodizzle/taskfile /tmp/taskfile
        else
          cd /tmp/taskfile && git pull
        fi
      - code /tmp/taskfile/Taskfile.yaml

  commit-taskfile:
    desc: Add Taskfile.yaml, commit it, and push to GitHub
    dir: /tmp/taskfile/
    cmds:
      - git add Taskfile.yaml
      - git commit -m "Update Taskfile.yaml"
      - git push origin main
      
  check-dir:
      desc: Check if a directory exists
      cmds:
        - test -d {{.DIR_PATH}} && echo "true" || echo "false"
      vars:
        DIR_PATH: "{{.DIR_PATH | default '.'}}"
